Repository ORNL/CabanaPD, pull requests merged in 2025-01, with the labels that each got.

#164 fixup: remove duplicate heat transfer construction
  src/CabanaPD_Solver.hpp
Labels: bug, ready for review

#152 Added critical time step for heat transfer
  examples/thermomechanics/inputs/thermal_deformation_heat_transfer.json
  src/CabanaPD_Input.hpp
  src/CabanaPD_Solver.hpp
Labels: ready for review

#165 fixup: missing unit input
  examples/mechanics/inputs/fragmenting_cylinder.json
Labels: ready for review

#139 Enable custom init in particle construction
  examples/mechanics/fragmenting_cylinder.cpp
  src/CabanaPD_Particles.hpp
  src/CabanaPD_Types.hpp
Labels: ready for review

#163 Rename model tags
  examples/mechanics/crack_branching.cpp
  examples/mechanics/elastic_wave.cpp
  examples/mechanics/fragmenting_cylinder.cpp
  examples/mechanics/kalthoff_winkler.cpp
  examples/thermomechanics/thermal_deformation.cpp
  examples/thermomechanics/thermal_deformation_heat_transfer.cpp
  src/CabanaPD_ForceModels.hpp
  src/CabanaPD_HeatTransfer.hpp
  src/CabanaPD_Solver.hpp
  src/CabanaPD_Types.hpp
  src/force/CabanaPD_ContactModels.hpp
  src/force/CabanaPD_ForceModels_LPS.hpp
  src/force/CabanaPD_ForceModels_PMB.hpp
  src/force/CabanaPD_Force_LPS.hpp
  src/force/CabanaPD_Force_PMB.hpp
  src/force/CabanaPD_HertzianContact.hpp
  unit_test/tstForce.hpp
  unit_test/tstHertz.hpp
Labels: ready for review

#181 readme: describe new capabilities
  README.md
Labels: documentation
